name: Conforméo CI (Tests & Build)

# 1. Quand est-ce que ça se déclenche ?
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  # --- JOB 1 : VÉRIFIER LE BACKEND (PYTHON) ---
  backend-check:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./backend

    steps:
    - uses: actions/checkout@v3

    - name: Installer Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Installer les dépendances
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    # On vérifie juste que le code n'a pas d'erreurs de syntaxe grossières
    - name: Vérification Syntaxique
      run: python -m compileall .

  # --- JOB 2 : VÉRIFIER LE MOBILE (IONIC/ANGULAR) ---
  mobile-build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./conformeo-mobile

    steps:
    - uses: actions/checkout@v3

    - name: Installer Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Installer Ionic CLI
      run: npm install -g @ionic/cli

    - name: Installer les dépendances (npm)
      run: npm install

    - name: Tenter de construire l'app (Build)
      # Si cette étape échoue, c'est que tu as cassé le code Angular
      run: ionic build --prod